[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "info"

[server]
headless = true
port = 10000
address = "0.0.0.0"
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
